// Copyright © Aptos
// SPDX-License-Identifier: Apache-2.0
export default function Head() {
  return (
    <>
      <title>Dapp Example Next.js</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
