name = "buy"
main = "src/worker.ts"
compatibility_date = "2023-06-07"
node_compat = true
usage_model = "bundled"

[vars]
MOONPAY_URL = "https://buy-sandbox.moonpay.com"

[env.production]
[env.production.vars]
MOONPAY_URL = "https://buy.moonpay.com"