name = "coingecko"
main = "src/index.ts"
compatibility_date = "2022-11-04"
node_compat = false
usage_model = "bundled"

# Other environment variables are defined as secrets and are not located here
# You must use wrangler secret put <KEY> or <KEY> --env production to add them
