source "https://rubygems.org"

ruby '>= 2.6.10'

gem "dotenv"

gem "fastlane"

gem 'cocoapods', '>= 1.11.3'

plugins_path = File.join(File.dirname(__FILE__), 'fastlane', 'Pluginfile')
eval_gemfile(plugins_path) if File.exist?(plugins_path)
